#pragma once

#include "Export.h"
#include "stdafx.h"

class Window;
class Camera;
class Object;
class Database;
class GPU;
class MeshSource;
class Mesh;
class Renderer;
class ShaderResource;
class Shader;
class StaticMesh;
class SyncLock;
class ScopeLock;
class Thread;
class Time;
class Transform;
class BBox3D;
class Config;

#include "Debugger.h"
#include "RenderLayer.h"
#include "Globals.h"
#include "Queue.h"
#include "BackedBuffer.h"
#include "BackedImage.h"
#include "RenderPass.h"
#include "GPU.h"
#include "AtomicLinkedList.h"
#include "Mesh.h"
#include "Shader.h"
#include "Renderer.h"
#include "Object.h"
#include "Database.h"
#include "Camera.h"
#include "Window.h"
#include "Config.h"
